[tool.poetry]
name = "botc-json2pdf"
version = "0.2.43"
description = ""
authors = ["Chisel <chisel@malik-wright.uk>"]
readme = "README.md"
packages = [{include = "botcpdf"}]

[tool.poetry.dependencies]
python = "^3.10"
jinja2 = "^3.1.2"
weasyprint = "^58.1"
pypdf = "^3.12.2"
pdf2image = "^1.16.3"
requests = "^2.28.2"
pytz = "^2023.3"
aws-lambda-powertools = "^2.19.0"
jmespath = "^1.0.1"
boto3 = "^1.26.164"
requests-toolbelt = "^1.0.0"
click = "^8.1.3"
discord-webhook = "^1.1.0"
aws-xray-sdk = "^2.12.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
pylint = "^2.17.2"
types-requests = "^2.31.0.0"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
