[tool.poetry]
name = "botc-json2pdf"
version = "0.0.13"
description = ""
authors = ["Chisel <chisel@malik-wright.uk>"]
readme = "README.md"
packages = [{include = "botcpdf"}]

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
weasyprint = "^58.1"
pypdf = "^3.8.0"
pdf2image = "^1.16.3"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
pylint = "^2.17.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
