---
service: botc-custom-script-json2pdf

provider:
  name: aws
  region: eu-west-2
  iam:
    role: arn:aws:iam::436158765452:role/botc/deploy_json2pdf
  ecr:
    scanOnPush: true
    images:
      json2pdf:
        path: ./
        file: Dockerfile
  stackTags:
    Name: botc-custom-script-json2pdf
    Owner: chisel
    Product: botc-custom-script-json2pdf
    InfoURL: https://github.com/chizmw/botc-custom-script-json2pdf

plugins:
  - serverless-docker

functions:
  botc-json2pdf:
    timeout: 15
    image:
      name: json2pdf
