---
name: DEBUG

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Path: ${{ github.event_path }}"
          cat ${{ github.event_path }}
