---
name: DEBUG

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Path: ${{ github.event_path }}"
          cat ${{ github.event_path }}

      - name: Add Event to Job Step Summary
        shell: bash
        run: |
          echo "```json" >> $GITHUB_STEP_SUMMARY
          cat ${{ github.event_path }} >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
