---
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  push:
    tags:
      - '*'

name: Deploy Serverless

jobs:
  linting:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - aws-account-name: chizography
            aws-account-id: 436158765452
            aws-deployment-role: botc/deploy_json2pdf

    steps:
      - uses: actions/checkout@v3

      # do this early so it can fail fast
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # yamllint disable rule:line-length
          aws-access-key-id: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ matrix.aws-account-id }}:role/${{ matrix.aws-deployment-role }}
          role-skip-session-tagging: true
          role-duration-seconds: 1800 # 30 minute session
          mask-aws-account-id: false
          # yamllint enable rule:line-length

      - name: Show AWS Credentials
        shell: bash
        run: |
          env |sort |grep AWS
          aws sts get-caller-identity

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set Environment Env
        # if we're a PR then we user 'dev', otherwise we use 'prod'
        # yamllint disable rule:line-length
        run: |
          # pull request
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "DEPLOY_ENV=dev" >> "$GITHUB_ENV"

          # push to default branch
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "DEPLOY_ENV=prod" >> "$GITHUB_ENV"

          # no idea what's going on
          else
            # ::error
            echo "::error::Unknown event type: ${{ github.event_name }} ${{ github.ref }}"
              exit 66
          fi
        # yamllint enable rule:line-length

      - name: SLS Prep
        shell: bash
        run: |
          npm --version
          npm install -g serverless@3
          serverless plugin install -n serverless-docker

      - name: Debug Matrix
        shell: bash
        run: |
          echo "::notice::aws-account-name: ${{matrix.aws-account-name}}"
          echo "::notice::aws-account-id: ${{matrix.aws-account-id}}"
          echo "::notice::aws-deployment-role: ${{matrix.aws-deployment-role}}"
          echo "::notice::DEPLOY_ENV: ${{env.DEPLOY_ENV}}"

      - name: SLS List Deploy
        shell: bash
        run: |
          sls deploy list

      - name: Install AWS RIE
        shell: bash
        # yamllint disable rule:line-length
        run: |
          mkdir -p ~/.aws-lambda-rie \
          && curl -Lo ~/.aws-lambda-rie/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie \
          && chmod +x ~/.aws-lambda-rie/aws-lambda-rie
        # yamllint enable rule:line-length

      - name: SLS Deploy (by env)
        shell: bash
        if: github.event_name == 'pull_request'
        run: |
          sls deploy --stage ${{ env.DEPLOY_ENV }}

      - name: Notify Discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          # yamllint disable rule:line-length
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1099136707108020305/r86TwsFW_T3BDX0VOvdcCNVFaGTLTSeVkwS8NikvynVrU-4jZLqq--FlyPVGAmQWJWu9
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: Deploy Serverless
          GITHUB_JOB_STATUS: ${{ job.status }}
