---
# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**/generated/**'
      - '**/.changes/**'
      - '**/README.md'
      - '**/CHANGELOG.md'

name: Run pre-commit checks

jobs:
  linting:
    name: run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          poetry install
      - uses: pre-commit/action@v3.0.0
