---
name: Terraform Matrix

# https://github.com/hashicorp/setup-terraform#setup-terraform

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform-matrix:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform-dir:
          - terraform
        include:
          - account-name-prefix: chizography
            session-tag: botc-json2pdf
            aws-account-id: 436158765452
            aws-deployment-role: botc/deploy_json2pdf

    steps:
      - uses: actions/checkout@v3

      - name: Set Workspace Env
        # if we're a PR then we user 'dev', otherwise we use 'prod'
        run: |
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "TF_WORKSPACE=dev" >> "$GITHUB_ENV"
          else
            echo "TF_WORKSPACE=prod" >> "$GITHUB_ENV"
          fi

      - name: Run terraform actions
        id: run-terraform-actions
        # yamllint disable-line rule:line-length
        uses: chizmw/terraform-workflow-action@37da56700f92c9236be112a41d19a4372b4354ef
        with:
          # yamllint disable rule:line-length
          use-workspaces: true
          workspace: ${{ env.TF_WORKSPACE }}
          terraform-dir: ${{ matrix.terraform-dir }}
          state-key: ${{ github.repository }}-${{ matrix.aws-account-id }}-${{ matrix.session-tag }}.tfstate
          aws-account-id: ${{ matrix.aws-account-id }}
          aws-account-name-prefix: ${{ matrix.account-name-prefix }}
          aws-session-tag: ${{ matrix.session-tag }}
          aws-access-key-id: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-deployment-role: ${{ matrix.aws-deployment-role }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # yamllint enable rule:line-length
