---
name: Terraform Matrix

# https://github.com/hashicorp/setup-terraform#setup-terraform

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform-matrix:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform-dir:
          - terraform
          - terraform/infra
          - terraform/velvetlookout.org
        include:
          - account-name-prefix: chizography
            session-tag: botc-json2pdf
            aws-account-id: 436158765452
            aws-deployment-role: botc/deploy_json2pdf

    steps:
      - uses: actions/checkout@v3

      - name: Run terraform actions
        id: run-terraform-actions
        # yamllint disable-line rule:line-length
        uses: chizmw/terraform-workflow-action@864120ce39c483176213b1b57f57f4215839d270
        with:
          # yamllint disable rule:line-length
          terraform-dir: ${{ matrix.terraform-dir }}
          state-key: ${{ github.repository }}-${{ matrix.aws-account-id }}-${{ matrix.session-tag }}.tfstate
          aws-account-id: ${{ matrix.aws-account-id }}
          aws-account-name-prefix: ${{ matrix.account-name-prefix }}
          aws-session-tag: ${{ matrix.session-tag }}
          aws-access-key-id: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-deployment-role: ${{ matrix.aws-deployment-role }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # yamllint enable rule:line-length
