---
name: Update Doc Version

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  readme-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git User
        uses: fregante/setup-git-user@v2

      # we use ourself to get the information for the release
      - name: Get Change Info
        uses: ./
        id: get-changelog-info

      - name: Update Version In Files
        shell: bash
        # yamllint disable rule:line-length
        run: |
          latest_version="${{ steps.get-changelog-info.outputs.last-change-version }}"
          files="README.md"

          # replace the version "latest-vx.y.z-blue" with the latest
          sed -i "s/latest-v.*-blue/latest-${latest_version}-blue/g" $files
        # yamllint enable rule:line-length

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          # yamllint disable rule:line-length
          title: 'chore: update version in files (${{ steps.get-changelog-info.outputs.last-change-version}})'
          commit-message: 'chore: update version in files (${{ steps.get-changelog-info.outputs.last-change-version}}) [skip ci]'
          base: ${{ github.event.repository.default_branch }}
          delete-branch: true
          token: ${{ secrets.CHANGESETS_TOKEN }}
          # yamllint enable rule:line-length

      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          # yamllint disable rule:line-length
          token: ${{ secrets.CHANGESETS_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          # yamllint enable rule:line-length
